[zshrc] Fix gwt, gwrm behavior. Add some rust stuff

diff --git a/linux/zshrc b/linux/zshrc
--- a/linux/zshrc
+++ b/linux/zshrc
@@ -190,6 +190,10 @@ source $ZSH/oh-my-zsh.sh
 # alias ohmyzsh="mate ~/.oh-my-zsh"
 
 
+export LI_API_KEY_PATH="${HOME}/li/api.key"
+export DISCORD_OAUTH_SECRET_PATH="${HOME}/li/discord-oauth"
+export SIGNING_KEY_PATH="${HOME}/li/test_forklift_signing_key"
+
 # # Add the dotnet-install.sh'd sdks to the PATH ...
 # export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
 # # ... and define the DOTNET_ROOT path based on that binary.
@@ -224,6 +228,7 @@ if [ -d "$HOME/.cargo/bin" ] ; then
     # shipped in the binaries you're running.
     export __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS="dev"
 fi
+export RUST_BACKTRACE=full
 
 # Set up Golang
 if [ -d "/usr/local/go" ]; then
@@ -256,7 +261,7 @@ fi
 source ${HOME}/repos/dotfiles/common/chirp/source.sh
 
 # Shortcut into the LI repo
-alias 0="cd ${HOME}/li/__repo_worktrees/main"
+alias 0="cd ${HOME}/li/repo"
 # Add LI binaries to PATH
 alias _src_li_dbg="export PATH=\"${PATH}:${HOME}/li/repo/target/debug\""
 alias _src_li_rel="export PATH=\"${PATH}:${HOME}/li/repo/target/release\""
@@ -402,15 +407,34 @@ function gwt {
         echo "ERROR: \`gwt\` requires exactuly 1 argument"
         return 1
     fi
-    while read -r wt; do
-        IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
-        wt_br=$(echo ${wt_br} | tr -d '[]');
-        if [ "$1" = "${wt_br}" ]; then
-            cd ${wt_path}
-            return
-        fi
-    done <<< $(git worktree list)
-    wt_root=$(__gw_get_worktrees_root)
+
+    if [[ "$1" = "sha-"* ]]; then
+        # If the given arg starts with `sha-`, we have to munge the input and
+        # match on worktree sha, rather than worktree branch.
+        local sha=${1#"sha-"}
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$sha" = "${wt_sha}" ]; then
+                cd ${wt_path}
+                return
+            fi
+        done <<< $(git worktree list)
+        echo "ERROR: failed to find a worktree matching the sha ${sha}"
+        return 1
+    else
+        # If the given arg isn't a sha, we can just match on branch.
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$1" = "${wt_br}" ]; then
+                cd ${wt_path}
+                return
+            fi
+        done <<< $(git worktree list)
+    fi
+
+    local wt_root=$(__gw_get_worktrees_root)
     git worktree add ${wt_root}/$1 $1
     if [ $? -eq 0 ]; then
         cd ${wt_root}/$1
@@ -422,15 +446,19 @@ function _gwt_completion {
         return $?
     fi
 
-    local -a options
-
-    worktree_branches=$(
-        # List all active worktree branches
-        git worktree list |
-        # But only the short branchname
-        xargs -I {} sh -c 'echo {} | awk "{print \$3}" | tr -d "[]"'
+    local wt_root=$(__gw_get_worktrees_root)
+    local worktree_identifiers=$(
+        # List all active worktrees
+        git worktree list |\
+        # EITHER take the branch shortname
+        perl -p -e 's/(.*?) +.* +\[(.*?)\]/$2:$1/' |\
+        # OR     take the sha prefixed with 'sha-'
+        perl -p -e 's/(.*?) +(.*?) +\((.*?)\)/sha-$2:$1 \($3\)/' |\
+        # Strip HOME and the worktree root from the recorded paths
+        perl -p -e "s#${wt_root}#@#" |\
+        perl -p -e "s#${HOME}#~#"
     )
-    all_branches=$(
+    local all_branches=$(
         git branch --sort -committerdate --all |
         # Stripping the worktree active in this dir
         rg -v '\*' |
@@ -439,16 +467,25 @@ function _gwt_completion {
         # Stripping alias'ing refs (e.g. `origin/HEAD`)
         rg -v " -> " |
         # Stripping e.g. remotes/origin/ s.t. we're left with just the branch names
-        xargs -I {} sh -c "echo {} | perl -pe 's;remotes/\w+/;;'"
+        perl -p -e 's;remotes/\w+/;;'|\
+        # Not sure if trimming whitespace is important, but I like doing it
+        tr -d ' '
     )
-    choices=$(
+    # Generate a newline-separated list of all choices
+    local choices=$(
         # Cat the existing branches with all possible branches
-        echo "${worktree_branches}\n${all_branches}" |
+        echo "${worktree_identifiers}\n${all_branches}" |
         # Listing unique entries while maintaining order (thanks S.O.)
+        # TODO: this won't remove branches that match existing worktrees
         awk '!seen[$0]++'
     )
+    # Convert the newline-separated-string-of-strings into an array
+    local -a options
+    options=()
+    while read -r choice; do
+        options+=("${choice}");
+    done <<< ${choices}
 
-    options=($(echo ${choices}))
     _describe -1V 'arguments' options
 }
 compdef _gwt_completion gwt
@@ -463,28 +500,106 @@ function gwrm {
         echo "ERROR: \`gwrm\` requires exactuly 1 argument"
         return 1
     fi
-    worktree_count=$(git worktree list | wc -l)
+    local worktree_count=$(git worktree list | wc -l)
     if [ $worktree_count -eq 1 ]; then
         echo "ERROR: do you really want to delete the last active worktree?"
         return 1
     fi
-    while read -r wt; do
-        IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
-        wt_br=$(echo ${wt_br} | tr -d '[]');
-        if [ "$1" = "${wt_br}" ]; then
-            # If we're within the worktree we're looking to remove, move to the
-            # first worktree listed in `git worktree list` before doing the rm.
-            if [[ "$(pwd)" == "${wt_root}/${wt_path}"* ]]; then
-                cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+    if [[ "$1" = "sha-"* ]]; then
+        # If the given arg starts with `sha-`, we have to munge the input and
+        # match on worktree sha, rather than worktree branch.
+        local sha=${1#"sha-"}
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$sha" = "${wt_sha}" ]; then
+                # If we're within the worktree we're looking to remove, move to
+                # the first listed worktree before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path}
+                return
             fi
-            git worktree remove ${wt_path}
-            git br -D ${wt_br}
+        done <<< $(git worktree list)
+        echo "ERROR: failed to find a worktree matching the sha ${sha}"
+        return 1
+    else
+        # If the given arg isn't a sha, we can just match on branch.
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$1" = "${wt_br}" ]; then
+                # If we're within the worktree we're looking to remove, move tothe
+                # the first listed worktree listed before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path}
 
-            return 0
-        fi
-    done <<< $(git worktree list)
+                return 0
+            fi
+        done <<< $(git worktree list)
+    fi
+    echo "ERROR: failed to find a worktree matching '$1'"
+    return 1
 }
+function gwrmb {
+    git rev-parse 2>& /dev/null
+    if [ $? -ne 0 ]; then
+        echo "ERROR: it looks like you're not in a git repo?"
+        return $?
+    fi
+    if [ $# -ne 1 ]; then
+        echo "ERROR: \`gwrm\` requires exactuly 1 argument"
+        return 1
+    fi
+    local worktree_count=$(git worktree list | wc -l)
+    if [ $worktree_count -eq 1 ]; then
+        echo "ERROR: do you really want to delete the last active worktree?"
+        return 1
+    fi
+    if [[ "$1" = "sha-"* ]]; then
+        # If the given arg starts with `sha-`, we have to munge the input and
+        # match on worktree sha, rather than worktree branch.
+        local sha=${1#"sha-"}
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$sha" = "${wt_sha}" ]; then
+                # If we're within the worktree we're looking to remove, move to
+                # the first listed worktree before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path}
+                echo "WARNING: calling gwrmb with a SHA means we can't delete branches"
+                return
+            fi
+        done <<< $(git worktree list)
+        echo "ERROR: failed to find a worktree matching the sha ${sha}"
+        return 1
+    else
+        # If the given arg isn't a sha, we can just match on branch.
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$1" = "${wt_br}" ]; then
+                # If we're within the worktree we're looking to remove, move tothe
+                # the first listed worktree listed before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path}
+                git br -D ${wt_br}
 
+                return 0
+            fi
+        done <<< $(git worktree list)
+    fi
+    echo "ERROR: failed to find a worktree matching '$1'"
+    return 1
+}
 function gwrf {
     git rev-parse 2>& /dev/null
     if [ $? -ne 0 ]; then
@@ -495,26 +610,51 @@ function gwrf {
         echo "ERROR: \`gwrm\` requires exactuly 1 argument"
         return 1
     fi
-    worktree_count=$(git worktree list | wc -l)
+    local worktree_count=$(git worktree list | wc -l)
     if [ $worktree_count -eq 1 ]; then
         echo "ERROR: do you really want to delete the last active worktree?"
         return 1
     fi
-    while read -r wt; do
-        IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
-        wt_br=$(echo ${wt_br} | tr -d '[]');
-        if [ "$1" = "${wt_br}" ]; then
-            # If we're within the worktree we're looking to remove, move to the
-            # first worktree listed in `git worktree list` before doing the rm.
-            if [[ "$(pwd)" == "${wt_root}"* ]]; then
-                cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+    if [[ "$1" = "sha-"* ]]; then
+        # If the given arg starts with `sha-`, we have to munge the input and
+        # match on worktree sha, rather than worktree branch.
+        sha=${1#"sha-"}
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$sha" = "${wt_sha}" ]; then
+                # If we're within the worktree we're looking to remove, move to
+                # the first listed worktree before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path} --force
+                echo "WARNING: calling gwrf with a SHA means we can't delete branches"
+                return
             fi
-            git worktree remove ${wt_path} --force
-            git br -D ${wt_br}
+        done <<< $(git worktree list)
+        echo "ERROR: failed to find a worktree matching the sha ${sha}"
+        return 1
+    else
+        # If the given arg isn't a sha, we can just match on branch.
+        while read -r wt; do
+            IFS=' ' read -r wt_path wt_sha wt_br <<< "${wt}"
+            local wt_br=$(echo ${wt_br} | tr -d '[]');
+            if [ "$1" = "${wt_br}" ]; then
+                # If we're within the worktree we're looking to remove, move tothe
+                # the first listed worktree listed before doing the rm.
+                if [[ "$(pwd)" == "${wt_path}"* ]]; then
+                    cd $(git worktree list | head -1 | cut -d ' ' -f 1)
+                fi
+                git worktree remove ${wt_path} --force
+                git br -D ${wt_br}
 
-            return 0
-        fi
-    done <<< $(git worktree list)
+                return 0
+            fi
+        done <<< $(git worktree list)
+    fi
+    echo "ERROR: failed to find a worktree matching '$1'"
+    return 1
 }
 function _gwrm_completion {
     git rev-parse 2>& /dev/null
@@ -522,12 +662,29 @@ function _gwrm_completion {
         return $?
     fi
 
+    local wt_root=$(__gw_get_worktrees_root)
+    local worktree_identifiers=$(
+        # List all active worktrees
+        git worktree list |\
+        # EITHER take the branch shortname
+        perl -p -e 's/(.*?) +.* +\[(.*?)\]/$2:$1/' |\
+        # OR     take the sha prefixed with 'sha-'
+        perl -p -e 's/(.*?) +(.*?) +\((.*?)\)/sha-$2:$1 \($3\)/' |\
+        # Strip HOME and the worktree root from the recorded paths
+        perl -p -e "s#${wt_root}#@#" |\
+        perl -p -e "s#${HOME}#~#"
+    )
+    # Convert the newline-separated-string-of-strings into an array
     local -a options
-    options=($(git worktree list | xargs -I {} sh -c 'echo {} | awk "{print \$3}" | tr -d "[]"'))
+    options=()
+    while read -r choice; do
+        options+=("${choice}");
+    done <<< ${worktree_identifiers}
 
-    _describe -V 'arguments' options
+    _describe -1V 'arguments' options
 }
 compdef _gwrm_completion gwrm
+compdef _gwrm_completion gwrmb
 compdef _gwrm_completion gwrf
 
 function gwnb {
@@ -541,7 +698,7 @@ function gwnb {
         return 1
     fi
 
-    wt_root=$(__gw_get_worktrees_root)
+    local wt_root=$(__gw_get_worktrees_root)
     git worktree add -b $1 ${wt_root}/$1 $2
     if [ $? -eq 0 ]; then
         cd ${wt_root}/$1
